config/routes.rb
Rails.application.routes.draw do
  

  get 'questions/submit'

  get 'questions/approve'

  get 'questions/reject'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } , :path => 'u'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get 'new_game' => 'home#new_game'
  get 'current_games' => 'home#current_games'
  get 'past_games' => 'home#past_games'
  get 'settings' => 'home#settings'
  get 'stats' => 'home#stats'
  get 'trophies' => 'home#trophies'
  get 'question_submit' => 'questions#new'#'home#question_submit'
  
  get 'admin' => 'users#index'  #home#admin'
  get 'question_review' => 'questions#review'
  post 'question_approve' => 'questions#approve'
  get 'question_reject' => 'questions#reject'

  
  get 'admin_save_user' => 'users#admin_save'
  get 'profile' => 'users#profile'
  
  get 'overall_stats' => 'stats#overall'
  get 'overall_total_stats' => 'stats#overall_total'
  get 'overall_art_stats' => 'stats#overall_art'
  get 'overall_sports_stats' => 'stats#overall_sports'
  get 'overall_entertainment_stats' => 'stats#overall_entertainment'
  get 'overall_geography_stats' => 'stats#overall_geography'
  get 'overall_science_stats' => 'stats#overall_science'
  get 'overall_history_stats' => 'stats#overall_history'
  get 'monthly_stats' => 'stats#monthly'
  get 'monthly_total_stats' => 'stats#monthly_total'
  get 'monthly_art_stats' => 'stats#monthly_art'
  get 'monthly_sports_stats' => 'stats#monthly_sports'
  get 'monthly_entertainment_stats' => 'stats#monthly_entertainment'
  get 'monthly_geography_stats' => 'stats#monthly_geography'
  get 'monthly_science_stats' => 'stats#monthly_science'
  get 'monthly_history_stats' => 'stats#monthly_history'
  get 'weekly_stats' => 'stats#weekly'
  get 'weekly_total_stats' => 'stats#weekly_total'
  get 'weekly_art_stats' => 'stats#weekly_art'
  get 'weekly_sports_stats' => 'stats#weekly_sports'
  get 'weekly_entertainment_stats' => 'stats#weekly_entertainment'
  get 'weekly_geography_stats' => 'stats#weekly_geography'
  get 'weekly_science_stats' => 'stats#weekly_science'
  get 'weekly_history_stats' => 'stats#weekly_history'
  

  resources :sessions, only: [:create, :destroy]
  resources :home do
    get :tests, on: :collection
  
  end
  
  resources :games do
    get :question, on: :collection
    get :ajax_spinner, on: :collection
    get :timer, on: :collection
    get :rate_question_and_redirect_to_spinner, on: :collection
  end
  

  resources :questions  
  resources :games
  

  get 'resign' => 'games#resign'
  get 'category_spinner' => 'games#category_spinner'
  get 'games_show' => 'games#show'
  get 'games_create' => 'games#create'
  get 'games_question' => 'games#question'
  get 'check_answer' => 'games#check_answer'
  get 'search' => 'home#new_game'
  get 'crown_category_choice' =>'games#crown_category_choice'
  get 'challenge' =>'challenges#challenge'
  get 'select_challenge_categories' => 'challenges#select_challenge_categories'
  get 'random_opponent' => 'games#random_opponent'
  get 'player_rate_question' => 'games#player_rate_question'
  get 'retry' => 'games#retry'
  get 'reset_powerup' => 'games#reset_powerup'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  
  resources :users
  get 'edit_users' => 'users#edit'
  get 'modify_user' => 'users#modify_user'
  get 'achievements' => 'users#achievements'
  get 'user_stats' => 'users#stats'
  get 'update_settings' => 'users#update_settings'
  get 'checkout' => 'users#checkout'

  root to: "home#show"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
		 :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end
  end
  def self.search(search)
    where("email like ? or name like ?", "%#{search}%", "%#{search}%")
  end

  #def paypal_url(return_url)
   # values = {
    #  :business => 'themphi-facilitator@my.westga.edu',
     #   :cmd => '_cart',
      #:upload => 1,
      #:return => return_url
    #} 
    # For test transactions use this url
    #{}"https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  #end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    
  end

  def checkout
    current_user.update_attribute(:coins, current_user.coins + 5)
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    
  end

  def edit
    @user = User.find(params[:format])
  end

  def update_settings
    @sound_flag = params[:sound_flag]
    current_user.sound_flag = @sound_flag
    current_user.save
    redirect_to settings_path
  end

  def update
    @user = User.find(params[:id])
    #byebug # check params[user]
    @user.update_attribute(:name, params[:user][:name])
    @user.update_attribute(:email, params[:user][:email])
    @user.update_attribute(:location, params[:user][:location])
    @user.update_attribute(:picture_privacy, params[:user][:picture_privacy])
    @user.update_attribute(:location_privacy, params[:user][:location_privacy])
    if params[:user][:password] == params[:user][:password_confirmation]
      @user.update_attribute(:password, params[:user][:password])
    end
    redirect_to root_path
    
  end
  
  def modify_user
    
    @user = User.find(params[:id])
    if(params[:access_level] == 'User')
      @user.update_attribute(:access_level, 0)
    elsif(params[:access_level] == 'Reviewer')
      @user.update_attribute(:access_level, 1)
    elsif(params[:access_level] == 'Admin')
      @user.update_attribute(:access_level, 2)
    else
      @user.update_attribute(:access_level, 3)
    end
    
    if @user.save
      redirect_to admin_path
    end
  end

  def index
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to user_path
  end
  
  def admin_save
    @user = User.find(params[:format])
    
    if(params[:access_level].to_str == 'User')
      @user.update_attribute(:access_level, 0)
    elsif(params[:access_level].to_str == 'Reviewer')
      @user.update_attribute(:access_level, 1)
    elsif(params[:access_level].to_str == 'Admin')
      @user.update_attribute(:access_level, 2)
    else
      @user.update_attribute(:access_level, 3)
    end
    if @user.save
      redirect_to admin_path
    end
  end
  
  def profile
    @user = User.find(params[:format])
    @stats = PlayerStats.where(user_id: params[:format]).first
    if @user.id != current_user.id
      @wins = Game.where(winningplayer_id: current_user.id, losingplayer_id: @user.id).length
      @losses = Game.where(winningplayer_id: @user.id, losingplayer_id: current_user.id).length
    end
    #byebug
  end
  
  def achievements
    @user = User.find(params[:format])
    @stats = PlayerStats.where(user_id: @user.id).first
    #byebug
  end
  
  def stats
    @user = User.find(params[:format])
    @stats = PlayerStats.where(user_id: @user.id).first
    
    if @stats.art_attempted > 0
      @art_avg = (@stats.art_correct.to_f / @stats.art_attempted) * 100
    else
      @art_avg = 0
    end
    if @stats.sports_attempted > 0
      @sport_avg = (@stats.sports_correct.to_f / @stats.sports_attempted) * 100
    else
      @sport_avg = 0
    end
    if @stats.entertainment_attempted > 0
      @ent_avg = (@stats.entertainment_correct.to_f / @stats.entertainment_attempted) * 100
    else
      @ent_avg = 0
    end
    if @stats.geography_attempted > 0
      @geo_avg = (@stats.geography_correct.to_f / @stats.geography_attempted) * 100
    else
      @geo_avg = 0
    end
    if @stats.science_attempted > 0
      @sci_avg = (@stats.science_correct.to_f / @stats.science_attempted) * 100
    else
      @sci_avg = 0
    end
    if @stats.history_attempted > 0
      @hist_avg = (@stats.history_correct.to_f / @stats.history_attempted) * 100
    else
      @hist_avg = 0
    end
    if @stats.total_attempted > 0
      @total_avg = (@stats.total_correct.to_f / @stats.total_attempted) * 100
    else
      @total_avg = 0
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :access_level,
                                   :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/achievements.html.erb
<h2>Achievements for <%= @user.email %></h2>

<% if @stats.art_achievement %>
  <h4>Achievement unlocked:  Artiste!</h4>
<% end %>
<% if @stats.sports_achievement %>
  <h4>Achievement unlocked:  Athlete</h4>
<% end %>
<% if @stats.entertainment_achievement %>
  <h4>Achievement unlocked:  Cultured Persona</h4>
<% end %>
<% if @stats.geography_achievement %>
  <h4>Achievement unlocked:  World Traveler</h4>
<% end %>
<% if @stats.science_achievement %>
  <h4>Achievement unlocked:  Evil Genius</h4>
<% end %>
<% if @stats.history_achievement %>
  <h4>Achievement unlocked:  History Buff</h4>
<% end %>
<% if @stats.total_achievement %>
  <h4>Achievement unlocked:  Grandmaster</h4>
<% end %>

<%= link_to "Back", profile_path(@user) %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :picture_privacy %>
      <%= f.check_box :picture_privacy, class: 'form-control' %>
      
      <%= f.label :location_privacy %>
      <%= f.check_box :location_privacy, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/index.html.erb
<h1>Admin</h1>

<table>
<% User.find_each do |user|%>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
    <td><%= user.access_level %></td>
    <td><%=link_to "Show", user_path(user) %></td>
    
    <td><%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/profile.html.erb
<% if !@user.picture_privacy? %>
  <%= gravatar_for(@user) %>
<% end %>
<h3>Personal information</h3>
<h4>Email: <%= @user.email %></h4>
<h4>Name: <%= @user.name %></h4>
<% if !@user.location_privacy? %>
  <h4>Location: <%= @user.location %></h4>
<% end %>
<h4>Difficulty Level: <%= @stats.level %></h4>

<% if @user.id == current_user.id %>
  <h4><%= link_to "Edit your information and settings", edit_users_path(@user) %></h4>
  
  <h4><%= link_to "Delete your account", @user, method: :delete,
                                  data: { confirm: "You sure?" } %></h4>
<% else %>
  <h4><%= link_to "Play a game against this person!", 
    games_create_path(:game => {:player1_id => current_user.id, :player2_id => @user.id, :currentplayer_id =>current_user.id}) %></h4>
  <h4>Your record against this opponent: <%= @wins %> Wins and <%= @losses %> Losses.</h4>
<% end %>


<h4><%= link_to "Achievements", achievements_path(@user.id) %></h4>
<h4><%= link_to "Statistics", user_stats_path(@user.id) %></h4>

app/views/users/show.html.erb
<h1>User Profile</h1>

<%= @user.email %>

<br>
<p>Set user permissions:</p>
<%#= form_for(@user) do |f| %>
  <%#= f.select :access_level, options_for_select(['User', 'Reviewer', 'Admin']) %>
  <% #@user.update_attribute(:access_level, f.select) %>
  <p><%# link_to "Save", admin_save_user_path(params[:id], :access_level) %></p>
  <%#= f.submit "Update user access", class: "btn btn-primary"%>


<%= form_tag(modify_user_path, :method => 'get') do %>
  <% options = options_for_select(['User', 'Reviewer', 'Admin']) %>
  <%= select_tag(:access_level, options) %>
  <%= hidden_field_tag :id, @user.id %>
<%= submit_tag "Update user access", class: "btn btn-primary" %>
<% end %>
<br>

<p><%= link_to "Delete", @user, method: :delete,
                                  data: { confirm: "You sure?" } %></p>

app/views/users/stats.html.erb
<h2>Statistics for <%= @user.email %></h2>

<h4>Percentage Correct</h4>
<p>Art: <%= @art_avg %>%</p>
<p>Sports: <%= @sport_avg %>%</p>
<p>Entertainment: <%= @ent_avg %>%</p>
<p>Geography: <%= @geo_avg %>%</p>
<p>Science: <%= @sci_avg %>%</p>
<p>History: <%= @hist_avg %>%</p>
<p>Total: <%= @total_avg %>%</p>

<h4>Total Correct</h4>
<p>Art: <%= @stats.art_correct  %></p>
<p>Sports: <%=  @stats.sports_correct %></p>
<p>Entertainment: <%= @stats.entertainment_correct  %></p>
<p>Geography: <%= @stats.geography_correct  %></p>
<p>Science: <%= @stats.science_correct  %></p>
<p>History: <%= @stats.history_correct  %></p>
<p>Total: <%= @stats.total_correct  %></p>

<%= link_to "Back", profile_path(@user) %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>