config/routes.rb
Rails.application.routes.draw do
  

  get 'questions/submit'

  get 'questions/approve'

  get 'questions/reject'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } , :path => 'u'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get 'new_game' => 'home#new_game'
  get 'current_games' => 'home#current_games'
  get 'past_games' => 'home#past_games'
  get 'settings' => 'home#settings'
  get 'stats' => 'home#stats'
  get 'trophies' => 'home#trophies'
  get 'question_submit' => 'questions#new'#'home#question_submit'
  
  get 'admin' => 'users#index'  #home#admin'
  get 'question_review' => 'questions#review'
  post 'question_approve' => 'questions#approve'
  get 'question_reject' => 'questions#reject'

  
  get 'admin_save_user' => 'users#admin_save'
  get 'profile' => 'users#profile'
  
  get 'overall_stats' => 'stats#overall'
  get 'overall_total_stats' => 'stats#overall_total'
  get 'overall_art_stats' => 'stats#overall_art'
  get 'overall_sports_stats' => 'stats#overall_sports'
  get 'overall_entertainment_stats' => 'stats#overall_entertainment'
  get 'overall_geography_stats' => 'stats#overall_geography'
  get 'overall_science_stats' => 'stats#overall_science'
  get 'overall_history_stats' => 'stats#overall_history'
  get 'monthly_stats' => 'stats#monthly'
  get 'monthly_total_stats' => 'stats#monthly_total'
  get 'monthly_art_stats' => 'stats#monthly_art'
  get 'monthly_sports_stats' => 'stats#monthly_sports'
  get 'monthly_entertainment_stats' => 'stats#monthly_entertainment'
  get 'monthly_geography_stats' => 'stats#monthly_geography'
  get 'monthly_science_stats' => 'stats#monthly_science'
  get 'monthly_history_stats' => 'stats#monthly_history'
  get 'weekly_stats' => 'stats#weekly'
  get 'weekly_total_stats' => 'stats#weekly_total'
  get 'weekly_art_stats' => 'stats#weekly_art'
  get 'weekly_sports_stats' => 'stats#weekly_sports'
  get 'weekly_entertainment_stats' => 'stats#weekly_entertainment'
  get 'weekly_geography_stats' => 'stats#weekly_geography'
  get 'weekly_science_stats' => 'stats#weekly_science'
  get 'weekly_history_stats' => 'stats#weekly_history'
  

  resources :sessions, only: [:create, :destroy]
  resources :home do
    get :tests, on: :collection
  
  end
  
  resources :games do
    get :question, on: :collection
    get :ajax_spinner, on: :collection
    get :timer, on: :collection
    get :rate_question_and_redirect_to_spinner, on: :collection
  end
  

  resources :questions  
  resources :games
  

  get 'resign' => 'games#resign'
  get 'category_spinner' => 'games#category_spinner'
  get 'games_show' => 'games#show'
  get 'games_create' => 'games#create'
  get 'games_question' => 'games#question'
  get 'check_answer' => 'games#check_answer'
  get 'search' => 'home#new_game'
  get 'crown_category_choice' =>'games#crown_category_choice'
  get 'challenge' =>'challenges#challenge'
  get 'select_challenge_categories' => 'challenges#select_challenge_categories'
  get 'random_opponent' => 'games#random_opponent'
  get 'player_rate_question' => 'games#player_rate_question'
  get 'retry' => 'games#retry'
  get 'reset_powerup' => 'games#reset_powerup'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  
  resources :users
  get 'edit_users' => 'users#edit'
  get 'modify_user' => 'users#modify_user'
  get 'achievements' => 'users#achievements'
  get 'user_stats' => 'users#stats'
  get 'update_settings' => 'users#update_settings'
  get 'checkout' => 'users#checkout'

  root to: "home#show"

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @questions = Question.all
    @stats = PlayerStats.where(:user_id => current_user.id)
    if @stats.empty?
      @stats = PlayerStats.new
      @stats.update_attribute(:user_id, current_user.id)
    end
    
  end
  def new_game
    if params[:alert]
      @alert = params[:alert]
    end
    if params[:search]
      @users = User.search(params[:search])
    else
      @users = Array.new
    end
  end
  def current_games
  end
  def past_games
  end
  def settings
    @sound_flag = current_user.sound_flag
  end
  def stats
  end
  def trophies
  end
  def question_submit
  end
  def question_review
  end
  def admin
  end
  def tests
    data = params[:test_data]
    respond_to do |format|
      format.json{
        render json: {
          text: data
        }
      }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<h2>Administration</h2>

<table>
<% User.find_each do |user|%>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.email %></td>
  </tr>
<% end %>
</table>

app/views/home/current_games.html.erb
<h1>Trivia Buster</h1>
<p>Current Games page.</p>

app/views/home/new_game.html.erb
  <p><h3>Start a new game</h3></p>
  <p>Search for a friend by name or email. Or play a random opponent:</p>
  <%= form_tag(search_path, :method => 'get') do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
    
  </p>
<% end %>
<%= button_to "Random", random_opponent_path(id: current_user.id), method: :get %>
<table>
  <% for user in @users %>
      <% if current_user.id != user.id %>
          <tr>
            <td><%#= link_to user.email, games_create_path(:game => {:player1_id => current_user.id, :player2_id => user.id, :currentplayer_id =>current_user.id}) %></td>
            <td><%= link_to user.email, profile_path(user) %></td>
          </tr>
      <% end %>
    <% end %>
</table>
<nav class="bad_alert"><%= @alert %> </nav>


  <p><h3>Games in progress</h3></p>
  <table>
    <% Game.where(player1_id: current_user.id, isfinished: false).find_each do |game|%>
      <% User.where(id: game.player2_id).find_each do |user|%>
          <% if game.currentplayer_id == current_user.id %> 
            <tr>
              <td><%= link_to user.email, category_spinner_path(id: game.id) %> (Your turn)</td>
            </tr>
          <% else %>
            <tr>
              <td><%= link_to user.email, category_spinner_path(id: game.id) %> (Their turn)</td>
            </tr>
          <% end %>
      <% end %>
    <% end %>
    <% Game.where(player2_id: current_user.id, isfinished: false).find_each do |game|%>
      <% User.where(id: game.player1_id).find_each do |user|%>
          <% if game.currentplayer_id == current_user.id %> 
            <tr>
              <td><%= link_to user.email, category_spinner_path(id: game.id) %> (Your turn)</td>
            </tr>
          <% else %>
            <tr>
              <td><%= link_to user.email, category_spinner_path(id: game.id) %> (Their turn)</td>
            </tr>
          <% end %>
      <% end %>
    <% end %>
  </table>

  <p><h3>Finished games</h3></p>
  <table>
    <% Game.where({player1_id: current_user.id, isfinished: true}).find_each do |game|%>
      <% User.where(id: game.player2_id).find_each do |user|%>
        <% if game.player1_id == game.winningplayer_id %>
          <tr>
            <td><%= link_to user.email, profile_path(user) %> (Won)</td>
          </tr>
        
        <% else %>
          <tr>
            <td><%= link_to user.email, profile_path(user) %> (Lost)</td>
          </tr>
          <% end %>
      <% end %>
    <% end %>
    <% Game.where({player2_id: current_user.id, isfinished: true}).find_each do |game|%>
      <% User.where(id: game.player1_id).find_each do |user|%>
        <% if game.player2_id == game.winningplayer_id %>
          <tr>
            <td><%= link_to user.email, profile_path(user) %> (Won)</td>
          </tr>
        <% else %>
          <tr>
            <td><%= link_to user.email, profile_path(user) %> (Lost)</td>
          </tr>
        <%  end %>
      <% end %>
    <% end %>
  </table>

app/views/home/past_games.html.erb
<h1>Trivia Buster</h1>
<p>Past Games page.</p>

app/views/home/question_review.html.erb
<h1>Review Questions</h1>
<table>
<% Question.find_each do |question|%>
  <tr>
    <td><%= question.id %></td>
    <td><%= question.username %></td>
    <td><%= question.question %></td>
    <td><%=link_to "Show", question_path(question) %></td>
    <td><%=link_to "Edit", edit_question_path(question) %></td>
    <td><%= link_to "Delete", question, method: :delete,
                                  data: { confirm: "You sure?" } %></td>
  </tr>
<% end %>
</table>

app/views/home/question_submit.html.erb
<h1>Trivia Buster</h1>
<p>Question Submission page.</p>

app/views/home/settings.html.erb
<h1>Settings</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag(update_settings_path, method: 'get') do %>
      <%#= render 'shared/error_messages' %>
      
      <%= label_tag :sound_flag %>
      <%= check_box_tag :sound_flag, @sound_flag, class: 'form-control' %>

      <%= submit_tag "Save changes", class: "btn btn-primary" %>
    <% end %>    
  </div>
</div>

app/views/home/show.html.erb
<p><%= link_to "Game",    new_game_path %></p>
<p><%= link_to "Game Settings",    settings_path %></p>
<p><%= link_to "Site Statistics",    stats_path %></p>
<p><%= link_to "Submit a Question",    question_submit_path %></p>
<% if current_user.access_level > 0 %>
  <p><%= link_to "Review Submitted Questions",    question_review_path %></p>
<% end %>
<% if current_user.access_level > 1 %>
  <p><%= link_to "Administrator Functions",    admin_path %></p>
<% end %>

<nav class="">

</nav>

Purchase Coins:
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
	<input type="hidden" name="cmd" value="_s-xclick">
	<input type="hidden" name="hosted_button_id" value="PXNV92E6L46YQ">
	<input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
	<img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>



<!--
<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
	<input type="hidden" name="cmd" value="_s-xclick">
	<input type="hidden" name="hosted_button_id" value="MZ457KSLN4MB2">
	<input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
	<img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>
-->

app/views/home/stats.html.erb
<h1>Statistics</h1>
<p><%= link_to "Overall Stats", overall_stats_path %></p>
<p><%= link_to "Monthly Stats", monthly_stats_path %></p>
<p><%= link_to "Weekly Stats", weekly_stats_path %></p>

app/views/home/trophies.html.erb
<h1>Trivia Buster</h1>
<p>Trophy page.</p>