config/routes.rb
Rails.application.routes.draw do
  

  get 'questions/submit'

  get 'questions/approve'

  get 'questions/reject'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } , :path => 'u'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get 'new_game' => 'home#new_game'
  get 'current_games' => 'home#current_games'
  get 'past_games' => 'home#past_games'
  get 'settings' => 'home#settings'
  get 'stats' => 'home#stats'
  get 'trophies' => 'home#trophies'
  get 'question_submit' => 'questions#new'#'home#question_submit'
  
  get 'admin' => 'users#index'  #home#admin'
  get 'question_review' => 'questions#review'
  post 'question_approve' => 'questions#approve'
  get 'question_reject' => 'questions#reject'

  
  get 'admin_save_user' => 'users#admin_save'
  get 'profile' => 'users#profile'
  
  get 'overall_stats' => 'stats#overall'
  get 'overall_total_stats' => 'stats#overall_total'
  get 'overall_art_stats' => 'stats#overall_art'
  get 'overall_sports_stats' => 'stats#overall_sports'
  get 'overall_entertainment_stats' => 'stats#overall_entertainment'
  get 'overall_geography_stats' => 'stats#overall_geography'
  get 'overall_science_stats' => 'stats#overall_science'
  get 'overall_history_stats' => 'stats#overall_history'
  get 'monthly_stats' => 'stats#monthly'
  get 'monthly_total_stats' => 'stats#monthly_total'
  get 'monthly_art_stats' => 'stats#monthly_art'
  get 'monthly_sports_stats' => 'stats#monthly_sports'
  get 'monthly_entertainment_stats' => 'stats#monthly_entertainment'
  get 'monthly_geography_stats' => 'stats#monthly_geography'
  get 'monthly_science_stats' => 'stats#monthly_science'
  get 'monthly_history_stats' => 'stats#monthly_history'
  get 'weekly_stats' => 'stats#weekly'
  get 'weekly_total_stats' => 'stats#weekly_total'
  get 'weekly_art_stats' => 'stats#weekly_art'
  get 'weekly_sports_stats' => 'stats#weekly_sports'
  get 'weekly_entertainment_stats' => 'stats#weekly_entertainment'
  get 'weekly_geography_stats' => 'stats#weekly_geography'
  get 'weekly_science_stats' => 'stats#weekly_science'
  get 'weekly_history_stats' => 'stats#weekly_history'
  

  resources :sessions, only: [:create, :destroy]
  resources :home do
    get :tests, on: :collection
  
  end
  
  resources :games do
    get :question, on: :collection
    get :ajax_spinner, on: :collection
    get :timer, on: :collection
    get :rate_question_and_redirect_to_spinner, on: :collection
  end
  

  resources :questions  
  resources :games
  

  get 'resign' => 'games#resign'
  get 'category_spinner' => 'games#category_spinner'
  get 'games_show' => 'games#show'
  get 'games_create' => 'games#create'
  get 'games_question' => 'games#question'
  get 'check_answer' => 'games#check_answer'
  get 'search' => 'home#new_game'
  get 'crown_category_choice' =>'games#crown_category_choice'
  get 'challenge' =>'challenges#challenge'
  get 'select_challenge_categories' => 'challenges#select_challenge_categories'
  get 'random_opponent' => 'games#random_opponent'
  get 'player_rate_question' => 'games#player_rate_question'
  get 'retry' => 'games#retry'
  get 'reset_powerup' => 'games#reset_powerup'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  
  resources :users
  get 'edit_users' => 'users#edit'
  get 'modify_user' => 'users#modify_user'
  get 'achievements' => 'users#achievements'
  get 'user_stats' => 'users#stats'
  get 'update_settings' => 'users#update_settings'
  get 'checkout' => 'users#checkout'

  root to: "home#show"

  

end

app/models/game.rb
class Game < ActiveRecord::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

	def resign
		
		@game = Game.find(params[:game_id])
		stats = PlayerStats.where(user_id: current_user.id).first
		@game.update_attribute(:losingplayer_id, @game.currentplayer_id)
		if @game.currentplayer_id == @game.player1_id
			@game.update_attribute(:winningplayer_id, @game.player2_id)
		else
			@game.update_attribute(:winningplayer_id, @game.player1_id)
		end
		stats.update_attribute(:resigns, stats.resigns + 1)
		stats.update_attribute(:losses, stats.losses + 1)
		@game.update_attribute(:isfinished, true)
		redirect_to root_path
	end

	def new
		@game = Game.new
	end

	def random_opponent
		@player1 = current_user
		@user_count = User.count
		if @user_count < 2
			redirect_to new_game_path(alert: "No other players available.")
		else
			@opponents = User.where.not(:id => @player1.id)
			@player2 = @opponents.shuffle.first
			@game = Game.new(player1_id: @player1.id, player2_id: @player2.id, currentplayer_id: @player1.id)
			if @game.save
				@player1_score = Score.new
				@player1_score.game_id = @game.id
				@player1_score.user_id = @game.player1_id
				@player2_score = Score.new
				@player2_score.game_id = @game.id
				@player2_score.user_id = @game.player2_id
				@player1_score.save
				@player2_score.save
				redirect_to category_spinner_path(id: @game.id)
			end
		end
		
	end

	def category_spinner
		if params[:alert]
			@alert = params[:alert]
		end
		 
		@game = Game.find(params[:id])
		@challenge = Challenge.where(game_id: @game.id, challenged_id: current_user.id, challenge_pending: true).first
		@player1 = User.find(@game.player1_id)
		@player2 = User.find(@game.player2_id)

		player1_stats = PlayerStats.where(user_id: @player1.id).first
		player2_stats = PlayerStats.where(user_id: @player2.id).first
		@score = Score.where({:user_id => current_user.id, :game_id => @game.id}).first
		
		if current_user.id == @player1.id
			@score2 = Score.where({:user_id => @player2.id, :game_id => @game.id}).first
		else
			@score2 = Score.where({:user_id => @player1.id, :game_id => @game.id}).first
		end
		
		if @score.points == 6
			@game.winningplayer_id = @score.user_id
			if @game.player1_id == @score.user_id
				player1_stats.update_attribute(:wins, player1_stats.wins + 1)
				@game.losingplayer_id = @game.player2_id
			elsif @game.player2_id == @score.user_id
				player2_stats.update_attribute(:wins, player2_stats.wins + 1)
				@game.losingplayer_id = @game.player1_id
			end
			@game.isfinished = true
			@game.save
			redirect_to new_game_path
		end
		if params[:crown_progress] #where would this param come from?
    		@score.crown_progress = 0
    		@score.save

		end

		if @game.nil?
			@game = Game.new(game_params)
			@game.save
		end
	end

	def crown_category_choice
		@game = Game.find(params[:id])
		@score = Score.find(params[:score_id])
		@score.crown_progress = 0
		@score.save
		@categories = Array.new
		if @score.sports_category == false
			@categories.push(Category.find(2))
			@category_id = 2
		end
		if @score.art_category == false
			@categories.push(Category.find(1))
			@category_id = 1
		end
		if @score.entertainment_category == false
			@categories.push(Category.find(3))
			@category_id = 3
		end
		if @score.science_category == false
			@categories.push(Category.find(5))
			@category_id = 5
		end
		if @score.history_category == false
			@categories.push(Category.find(6))
			@category_id = 6
		end
		if @score.geography_category == false
			@categories.push(Category.find(4))
			@category_id = 4
		end
	end

	def retry
		@game = Game.find(params[:id])
		@score = Score.where({:user_id => current_user.id, :game_id => @game.id}).first
		@question = Question.find(params[:question_id])
		@category_id = params[:category_id]
		@crown_question = params[:crown_question]
		@score.retry = true
		@score.save
		current_user.coins -= 15
		current_user.save
		redirect_to games_question_path(id: @game.id, question_id: @question.id, category_id: @category_id, crown_question: @crown_question)
	end

	def reset_powerup
		@game = Game.find(params[:id])
		@score = Score.where({:user_id => current_user.id, :game_id => @game.id}).first
		@question = Question.find(params[:question_id])
		@category_id = params[:category_id]
		@crown_question = params[:crown_question]
		@score.save
		current_user.coins -= 5
		current_user.save
		redirect_to games_question_path(id: @game.id, question_id: @question.id, category_id: @category_id, crown_question: @crown_question)
	end



	def question
		
		if params[:challenge_question] == "true"
			@game = Game.find(params[:id])
			@challenge = Challenge.find(params[:challenge_id])
			@current_player_id = params[:current_player_id]
			@challenge_question = params[:challenge_question]
			@question_number = params[:question_number]
				if @question_number == "1"
					@question = Question.find(@challenge.art_question_id)
				elsif @question_number == "2"
					@question = Question.find(@challenge.sports_question_id)
				elsif @question_number == "3"
					@question = Question.find(@challenge.entertainment_question_id)
				elsif @question_number == "4"
					@question = Question.find(@challenge.geography_question_id)
				elsif @question_number == "5"
					@question = Question.find(@challenge.science_question_id)
				elsif @question_number == "6"
					@question = Question.find(@challenge.history_question_id)
				end
			@amount_correct = params[:amount_correct]
		else
			stats = PlayerStats.where(user_id: current_user.id).first
			@game = Game.find(params[:id])
			if params[:category_id]
				@category_id = (params[:category_id].to_i % 7)
				if(@category_id == 0)
					@category_id = 7
				end
				
			else
				@category_id = rand(1..7)
			end
			if @category_id == 7
				@score = Score.where({:user_id => @game.currentplayer_id, :game_id => @game.id}).first
				redirect_to crown_category_choice_path({id: @game.id, score_id: @score.id})
			else
				@crown_question = params[:crown_question]
			 	@category = Category.find(@category_id)
			 	@user = User.find(@game.currentplayer_id)
			 	if params[:question_id]
			 		@question = Question.find(params[:question_id])
			 	else
			 		@questions = Question.where(category_id: @category.id, approved: true, level: stats.level).all
			 		@question = @questions.shuffle.first
			 	end
			end			
		end
	end

	def get_piece(score_id, category_id)
		@score = Score.find(score_id)
		if category_id == "1"
			@score.art_category = true
		end
		if category_id == "2"
			@score.sports_category = true
		end
		if category_id == "3"
			@score.entertainment_category = true
		end
		if category_id == "4"
			@score.geography_category = true
		end
		if category_id == "5"
			@score.science_category = true
		end
		if category_id == "6"
			@score.history_category = true
		end
		@score.points += 1
		@score.save
		
	end

	def change_turns(game_id, answer_id, question_id)
		@game = Game.find(game_id)
		if @game.currentplayer_id == @game.player1_id
			@game.currentplayer_id = @game.player2_id
			@game.save
			redirect_to player_rate_question_path(id: @game.id, answer_id: answer_id, question_id: question_id)#category_spinner_path(id: @game.id)
		elsif @game.currentplayer_id == @game.player2_id
			@game.currentplayer_id = @game.player1_id
			@game.save
			redirect_to player_rate_question_path(id: @game.id, answer_id: answer_id, question_id: question_id)
		else
			redirect_to new_game_path	
		end
	end

	def check_answer
		if params[:freeze_coins]
			current_user.update_attribute(:coins, current_user.coins - params[:freeze_coins].to_i)
		end
		@game = Game.find(params[:id])
		
		@crown_question = params[:crown_question]
		@score = Score.where({:user_id => current_user.id, :game_id => @game.id}).first
		
		if current_user.id != @game.currentplayer_id
			redirect_to category_spinner_path(id: @game.id)
		end

		if params[:challenge_question] == "true"
			@challenge = Challenge.find(params[:challenge_id])
			@current_player_id = params[:current_player_id]
			@challenge_question = params[:challenge_question]
			@question_number = params[:question_number]
			@amount_correct = params[:amount_correct]
			@answer = Answer.find(params[:answer])
			if @answer.correct?
				@amount_correct = @amount_correct.to_i + 1
				current_user.coins += 2
				current_user.save
				@score.save
			end
			redirect_to challenge_path(game_id: @game.id, question_number: @question_number, amount_correct: @amount_correct, challenge_id: @challenge.id, challenge_question: @challenge_question)

		else
			
			@category_id = params[:category_id]
			increase_user_total_attempted
			increase_category_attempted(@category_id)
			if params[:answer]
				@question = Question.find(params[:question_id])
				@answer = Answer.find(params[:answer])
				#user = User.find(@game.currentplayer_id)
				if params[:crown_question] == "true"
					if @answer.correct?
						increase_user_total_correct
						increase_category_correct(@category_id)
						get_piece(@score.id, @category_id)
						current_user.coins += 2
						current_user.save
						if @score.save
							#redirect_to category_spinner_path(id: @game.id)

							redirect_to player_rate_question_path(id: @game.id, question_id: params[:question_id], answer_id: @answer.id)
						end
					else
						@score.save
						change_turns(@game.id, @answer.id, params[:question_id])
						#change_turns(@game.id)
					end
				else
					if @answer.correct?
						increase_user_total_correct
						increase_category_correct(@category_id)
						@score.crown_progress += 1
						current_user.coins += 2
						current_user.save
						if @score.save
							#redirect_to category_spinner_path(id: @game.id)
							redirect_to player_rate_question_path(id: @game.id, question_id: params[:question_id], answer_id: @answer.id)
						end
					else
						if @score.retry?
							@score.retry = false
							@score.save
							redirect_to games_question_path(id: @game.id, question_id:@question.id, category_id: @category_id, crown_question: false)
						else

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/category_spinner.html.erb
<nav class="labels">
	<p>Player 1: <%= @player1.email %></p>
	<p>Player 2: <%= @player2.email %></p>
	<%= content_tag :div, class: "hidden_game_id", data: {id: @game.id} do %>
	<% end %>
	<%= content_tag :div, class: "hidden_sound_flag", data: {sound_flag: current_user.sound_flag} do %>
	<% end %>
	<!-- display pieces here -->
<table>
	<tr>
		<td>
			Player 1 Pieces: 
		</td>
		<td>
			<% if @score.art_category %>
		<nav class="art">Art</nav>
		<% end %>
		</td>
		<td>
			<% if @score.sports_category %>
		<nav class="sports">Sports</nav> 
		<% end %>
		</td>
		<td>
			<% if @score.entertainment_category %>
		<nav class="entertainment">Entertainment</nav>
		<% end %>
		</td>
		<td>
			<% if @score.geography_category %>
			<nav class="geography">Geography</nav>
		<% end %>
		</td>
		<td>
			<% if @score.science_category %>
			<nav class="science">Science</nav>
		<% end %>
		</td>
		<td>
			<% if @score.history_category %>
			<nav class="history">History</nav>
		<% end %>
		</td>
	</tr>
	<tr>
		<td>
			Player 2 Pieces: 
		</td>
		<td>
			<% if @score2.art_category %>
		<nav class="art">Art</nav>
		<% end %>
		</td>
		<td>
			<% if @score2.sports_category %>
		<nav class="sports">Sports</nav> 
		<% end %>
		</td>
		<td>
			<% if @score2.entertainment_category %>
		<nav class="entertainment">Entertainment</nav>
		<% end %>
		</td>
		<td>
			<% if @score2.geography_category %>
			<nav class="geography">Geography</nav>
		<% end %>
		</td>
		<td>
			<% if @score2.science_category %>
			<nav class="science">Science</nav>
		<% end %>
		</td>
		<td>
			<% if @score2.history_category %>
			<nav class="history">History</nav>
		<% end %>
		</td>
	</tr>

</table>
	
</nav>


<% if @score.crown_progress == 3 %>

<p><%= link_to "Crown", crown_category_choice_path(crown_progress: '3', id: @game.id, score_id: @score.id) %> or <%= link_to "Challenge", select_challenge_categories_path(:game_id => @game.id, :challenging_id => current_user.id)%></p>
<%else%>
	<% if @challenge.nil? %>
		<% if current_user.id == @game.currentplayer_id %>
	</br>
	  	<nav class="spinner">
	  		<div id="spinner">Category: <span class="art">Art</span></div>
			<button id='spinner_button'>Spin!</button>
			<br>
	  	</nav>
	  	<p><%#= link_to "Get Question", games_question_path(category_id: 6, id: @game.id, crown_question: false) %></p>
		<% else %>
			<p>Waiting for other player to answer</p>
		<% end %>
	<% else %>
		<p>You have a challenge pending <%= link_to "here", games_question_path(id: @game.id, question_id: @challenge.art_question_id, current_player_id: current_user.id, challenge_id: @challenge.id, challenge_question: true, question_number: 1, amount_correct: 0) %>.</p>
	<% end %>
	
<%end%>

<nav class="bad_alert"><%= @alert %> </nav>

<p>
	<h2>Crown Progress: </h2>
	<div class="row">
			<% if @score.crown_progress == 0 %>
				<div id="crown-progress-bar-1" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-2" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-3" class="col-xs-6 col-md-4">
					<div class="progress">
			  			<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
			<% elsif @score.crown_progress == 1 %>
				<div id="crown-progress-bar-1" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-2" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-3" class="col-xs-6 col-md-4">
					<div class="progress">
			  			<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
			<% elsif @score.crown_progress == 2 %>
				<div id="crown-progress-bar-1" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-2" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-3" class="col-xs-6 col-md-4">
					<div class="progress">
			  			<div class="progress-bar progress-bar-success" style="width: 0%"></div>
					</div>
				</div>
			<% else %>
				<div id="crown-progress-bar-1" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-2" class="col-xs-6 col-md-4">
					<div class="progress">
	  					<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
				<div id="crown-progress-bar-3" class="col-xs-6 col-md-4">
					<div class="progress">
			  			<div class="progress-bar progress-bar-success" style="width: 100%"></div>
					</div>
				</div>
			<% end %>
	</div>
</p>


<p><%= link_to "Resign Game", resign_path(game_id: @game.id) %></p>

app/views/games/crown_category_choice.html.erb
<%= form_tag(games_question_path, :method => 'get') do %>
<p><%= label_tag('Select the category you want to play for:') %></p>
<p>
  <% options = options_from_collection_for_select(@categories, :id, :name, :id) %>
  <%= select_tag(:category_id, options) %>
  <%= hidden_field_tag "id", @game.id %>
  <%= hidden_field_tag "crown_question", true %>
  <%#= hidden_field_tag "category_id", @category_id %>
</p>
<%= submit_tag "Submit", class: "btn btn-primary" %>
<% end %>

app/views/games/player_rate_question.html.erb
<nav class="rate_question">
<% if !!@answer %>
  <% if @answer.correct? %>
  <nav class="good_alert">
    <h4>You answered correctly!</h4>
  </nav>
    <% if current_user.sound_flag %>
      <audio id='win'>
        <source src='win.mp3' type='audio/mpeg'>
      </audio>
    <%end%>
  <% else %>
  <nav class="bad_alert">
    <h4>You answered wrong.</h4>
  </nav>
    <% if current_user.sound_flag %>
      <audio id='fail'>
        <source src='fail.mp3' type='audio/mpeg'>
      </audio>
    <%end%>
  <% end %>
<% else %>
  <nav class="bad_alert">
    <h4>You answered wrong.</h4>
  </nav>
<% end %>

<h4>Please rate this question:</h4>
<% options = options_for_select(['Just Right', 'Easy', 'Hard']) %>
<%= select_tag(:rating, options, id: 'rating_selector') %>
<%= content_tag :div, class: "hidden_player_rating_data", data: { id: @game_id, question_id: @question_id } do %><%end%>
<%#= content_tag :div, class: "hidden_player_rating_data", data: {  } do %><%#end%>
</br></br>
<button id='player_rating_button'>Rate question and continue</button>
</nav>

app/views/games/question.html.erb
<h4>Category: </h4>
<% if @category_id == 1 %>
    <h4>Art</h4>
<% elsif @category_id == 2 %>
    <h4>Sports</h4>
<% elsif @category_id == 3 %>
    <h4>Entertainment</h4>
<% elsif @category_id == 4 %>
    <h4>Geography</h4>
<% elsif @category_id == 5 %>
    <h4>Science</h4>
<% elsif @category_id == 6 %>
    <h4>History</h4>
<% end %>


<% if @challenge_question == "true" %>
    <%= form_tag(check_answer_path, :method => 'get') do %>
    <table>
    <% Question.where(id: @question.id).find_each do |question|%>
            <tr>
                <td><h3><%= question.question %></h3></td>
            </tr>
        <% Answer.where(question_id: question.id).shuffle.each do |answer|%>
        <tr>
            <td>
                <h4>
                    <%= radio_button_tag(:answer, answer.id) %>
                    <%= answer.answer_text %>

                    <%= hidden_field_tag "id", @game.id %>
                    <%= hidden_field_tag "challenge_id", @challenge.id %>
                    <%= hidden_field_tag "current_player_id", @current_player_id %>
                    <%= hidden_field_tag "challenge_question", @challenge_question %>
                    <%= hidden_field_tag "question_number", @question_number %>
                    <%= hidden_field_tag "amount_correct", @amount_correct %>
                    <%# hidden_field_tag "crown_question", @crown_question %>
                </h4>
            </td>
        </tr>

        <% end %>
    <% end %>
    </table>
    <%= submit_tag "Submit", class: "btn btn-primary" %>
    <% end %>
<% else %>
    <h4>Timer: <div id='timer'>30</div></h4>
    <%= form_tag(check_answer_path, :method => 'get') do %>
        <table>
        <% Question.where(id: @question.id).find_each do |question|%>
            <tr>
                <td><h3><%= question.question %></h3></td>
            </tr>
            <% Answer.where(question_id: question.id).shuffle.each do |answer|%>
                <tr>
                    <td>
                        <h4>
                            <%= radio_button_tag(:answer, answer.id) %>
                            <%= answer.answer_text %>
                            <%= content_tag :div, class: "hidden_timer_data", data: { id: @game.id} do %><%end%>
                            <%= content_tag :div, class: "hidden_timer_data", data: { category_id: @category.id} do %><%end%>
                            <%= content_tag :div, class: "hidden_timer_data", data: { crown_question: @crown_question} do %><%end%>
                            <%= content_tag :div, class: "hidden_timer_data", data: { question_id: @question.id} do %><%end%>
                            <%= content_tag :div, class: "hidden_timer_data", data: { answer_id: answer.id} do %><%end%>
                            <%= hidden_field_tag :id, @game.id %>
                            <%= hidden_field_tag :category_id, @category.id %>
                            <%= hidden_field_tag :crown_question, @crown_question %>
                            <%= hidden_field_tag :question_id, @question.id %>

                            <%#= hidden_field_tag :freeze_coins, 0 %>
                            <%#= hidden_field_tag "answer_chosen", true %>
                        </h4>
                    </td>
                </tr>
            <% end %>
        <% end %>
        </table>
        <%= hidden_field_tag :freeze_coins, 0 %>
        <%= submit_tag "Submit", class: "btn btn-primary" %>
    </br>
    </br>
    <% end %>
    <p>
        <% if current_user.coins >= 5 %>
            <%= link_to "Reset Time", reset_powerup_path(id: @game.id, category_id: @category.id, question_id: @question.id, crown_question: @crown_question), method: :get %> Cost: 5
        <% end %>
    </p>
    <p>
        <% if current_user.coins >= 10 %>
            <button id='freezer'>Freeze Time</button> Cost: 10
        <% end %>
    </p>
    <p>
        <% if current_user.coins >= 15 %>
            <%= link_to "Extra Try", retry_path(id: @game.id, category_id: @category.id, question_id: @question.id, crown_question: @crown_question), method: :get %> Cost: 15
        <% end %>
    </p>
    
    
    
<% end %>

<div class='freeze' id='freeze'>f</div>
<div class='freeze'>0</div>