config/routes.rb
Rails.application.routes.draw do
  

  get 'questions/submit'

  get 'questions/approve'

  get 'questions/reject'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" } , :path => 'u'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  
  get 'new_game' => 'home#new_game'
  get 'current_games' => 'home#current_games'
  get 'past_games' => 'home#past_games'
  get 'settings' => 'home#settings'
  get 'stats' => 'home#stats'
  get 'trophies' => 'home#trophies'
  get 'question_submit' => 'questions#new'#'home#question_submit'
  
  get 'admin' => 'users#index'  #home#admin'
  get 'question_review' => 'questions#review'
  post 'question_approve' => 'questions#approve'
  get 'question_reject' => 'questions#reject'

  
  get 'admin_save_user' => 'users#admin_save'
  get 'profile' => 'users#profile'
  
  get 'overall_stats' => 'stats#overall'
  get 'overall_total_stats' => 'stats#overall_total'
  get 'overall_art_stats' => 'stats#overall_art'
  get 'overall_sports_stats' => 'stats#overall_sports'
  get 'overall_entertainment_stats' => 'stats#overall_entertainment'
  get 'overall_geography_stats' => 'stats#overall_geography'
  get 'overall_science_stats' => 'stats#overall_science'
  get 'overall_history_stats' => 'stats#overall_history'
  get 'monthly_stats' => 'stats#monthly'
  get 'monthly_total_stats' => 'stats#monthly_total'
  get 'monthly_art_stats' => 'stats#monthly_art'
  get 'monthly_sports_stats' => 'stats#monthly_sports'
  get 'monthly_entertainment_stats' => 'stats#monthly_entertainment'
  get 'monthly_geography_stats' => 'stats#monthly_geography'
  get 'monthly_science_stats' => 'stats#monthly_science'
  get 'monthly_history_stats' => 'stats#monthly_history'
  get 'weekly_stats' => 'stats#weekly'
  get 'weekly_total_stats' => 'stats#weekly_total'
  get 'weekly_art_stats' => 'stats#weekly_art'
  get 'weekly_sports_stats' => 'stats#weekly_sports'
  get 'weekly_entertainment_stats' => 'stats#weekly_entertainment'
  get 'weekly_geography_stats' => 'stats#weekly_geography'
  get 'weekly_science_stats' => 'stats#weekly_science'
  get 'weekly_history_stats' => 'stats#weekly_history'
  

  resources :sessions, only: [:create, :destroy]
  resources :home do
    get :tests, on: :collection
  
  end
  
  resources :games do
    get :question, on: :collection
    get :ajax_spinner, on: :collection
    get :timer, on: :collection
    get :rate_question_and_redirect_to_spinner, on: :collection
  end
  

  resources :questions  
  resources :games
  

  get 'resign' => 'games#resign'
  get 'category_spinner' => 'games#category_spinner'
  get 'games_show' => 'games#show'
  get 'games_create' => 'games#create'
  get 'games_question' => 'games#question'
  get 'check_answer' => 'games#check_answer'
  get 'search' => 'home#new_game'
  get 'crown_category_choice' =>'games#crown_category_choice'
  get 'challenge' =>'challenges#challenge'
  get 'select_challenge_categories' => 'challenges#select_challenge_categories'
  get 'random_opponent' => 'games#random_opponent'
  get 'player_rate_question' => 'games#player_rate_question'
  get 'retry' => 'games#retry'
  get 'reset_powerup' => 'games#reset_powerup'
  
  devise_scope :user do 
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  
  resources :users
  get 'edit_users' => 'users#edit'
  get 'modify_user' => 'users#modify_user'
  get 'achievements' => 'users#achievements'
  get 'user_stats' => 'users#stats'
  get 'update_settings' => 'users#update_settings'
  get 'checkout' => 'users#checkout'

  root to: "home#show"

  

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  def overall
  end
  
  def overall_art
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_sports
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_entertainment
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_geography
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_science
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_history
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def overall_total
    @stats = PlayerStats.order(:total_correct)
    @perc_stats = Hash.new
  end
  
  def monthly
  end
  
  def monthly_total
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.total_correct - first_snapshot.total_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.total_attempted - first_snapshot.total_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_art
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.art_correct - first_snapshot.art_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.art_attempted - first_snapshot.art_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_science
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.science_correct - first_snapshot.science_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.science_attempted - first_snapshot.science_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_sports
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.sports_correct - first_snapshot.sports_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.sports_attempted - first_snapshot.sports_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_history
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.history_correct - first_snapshot.history_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.history_attempted - first_snapshot.history_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_entertainment
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.entertainment_correct - first_snapshot.entertainment_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.entertainment_attempted - first_snapshot.entertainment_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def monthly_geography
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.geography_correct - first_snapshot.geography_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.geography_attempted - first_snapshot.geography_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def weekly
  end
  
  def weekly_art
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.art_correct - first_snapshot.art_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.art_attempted - first_snapshot.art_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def weekly_sports
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last
      #byebug
      if !first_snapshot
        @group_diff[user.id] = 0
        @group_perc[user.id] = 0
      else
        @group_diff[user.id] = last_snapshot.sports_correct - first_snapshot.sports_correct
        if @group_diff[user.id] > 0
          @group_perc[user.id] = 100 * (@group_diff[user.id]).to_f / (last_snapshot.sports_attempted - first_snapshot.sports_attempted)
        else
          @group_perc[user.id] = 0
        end
      end
      
    end
    @group_diff.sort_by { |k,v| v }
    @group_perc.sort_by { |k,v| v }
  end
  
  def weekly_science
    @monthly_stats = MonthlyPlayerStats.where(created_at: 1.month.ago..DateTime.now)#.order(:created_at)
    @group = Hash.new
    @group_diff = Hash.new
    @group_perc = Hash.new
    User.find_each do |user|
      @group[user.id] = @monthly_stats.where(user_id: user.id)
      first_snapshot = @group[user.id].order(:created_at).first
      last_snapshot = @group[user.id].order(:created_at).last

app/views/stats/monthly_art.html.erb
<h3>Monthly Art Stats</h3>

<h4>Email / Sum Art Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Art Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Monthly Stats", monthly_stats_path %>

app/views/stats/monthly_entertainment.html.erb
<h3>Monthly Entertainment Stats</h3>

<h4>Email / Sum Entertainment Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Entertainment Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Monthly Stats", monthly_stats_path %>

app/views/stats/monthly_science.html.erb
<h3>Monthly Science Stats </h3>

<h4>Email / Sum Science Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Science Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Monthly Stats", monthly_stats_path %>

app/views/stats/monthly_sports.html.erb
<h3>Monthly Sports Stats</h3>

<h4>Email / Sum Sports Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Sports Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Monthly Stats", monthly_stats_path %>

app/views/stats/monthly_total.html.erb
<h3>Monthly Total Stats</h3>

<h4>Email / Sum Total Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Total Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Monthly Stats", monthly_stats_path %>

app/views/stats/overall_entertainment.html.erb
<h3>Overall Entertainment Stats</h3>

<h4>Email  Sum Entertainment Correct</h4>
<% @stats.find_each do |stat| %>
  <p><%= User.find(stat.user_id).email %> <%= stat.entertainment_correct %></p>
  <% if stat.art_attempted > 0 %>
    <% @perc_stats[stat.user_id] =  ( 100 * stat.entertainment_correct.to_f / stat.entertainment_attempted ) %>
  <% else %>
    <% @perc_stats[stat.user_id] =  0 %>
  <% end %>
<% end %>

<% @perc_stats.sort_by {|k,v| v} %>

<h4>Email   Percent Entertainment Correct</h4>
<% @perc_stats.each do |id, perc| %>
  <p><%= User.find(id).email %> <%= perc %>%</p>
<% end %>

<%= link_to "Back to Overall Stats", overall_stats_path %>

app/views/stats/overall_total.html.erb
<h3>Overall Total Stats</h3>

<h4>Email / Sum Total Correct</h4>
<% @stats.find_each do |stat| %>
  <p><%= User.find(stat.user_id).email %> <%= stat.total_correct %></p>
  <% if stat.total_attempted > 0 %>
    <% @perc_stats[stat.user_id] =  ( 100 * stat.total_correct.to_f / stat.total_attempted ) %>
  <% else %>
    <% @perc_stats[stat.user_id] =  0 %>
  <% end %>
<% end %>

<% @perc_stats.sort_by {|k,v| v} %>

<h4>Email /  Percent Total Correct</h4>
<% @perc_stats.each do |id, perc| %>
  <p><%= User.find(id).email %> <%= perc %>%</p>
<% end %>

<%= link_to "Back to Overall Stats", overall_stats_path %>

app/views/stats/weekly.html.erb
<h3>Weekly Statistics</h3>
<p><%= link_to "Total Stats", weekly_total_stats_path %></p>
<p><%= link_to "Art Stats", weekly_art_stats_path %></p>
<p><%= link_to "Sports Stats", weekly_sports_stats_path %></p>
<p><%= link_to "Entertainment Stats", weekly_entertainment_stats_path %></p>
<p><%= link_to "Geography Stats", weekly_geography_stats_path %></p>
<p><%= link_to "Science Stats", weekly_science_stats_path %></p>
<p><%= link_to "History Stats", weekly_history_stats_path %></p>
<p><%= link_to "Back to Site Stats", stats_path %></p>

app/views/stats/weekly_art.html.erb
<h3>Weekly Art Stats</h3>

<h4>Email / Sum Art Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Art Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>

app/views/stats/weekly_entertainment.html.erb
<h3>Weekly Entertainment Stats</h3>

<h4>Email / Sum Entertainment Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Entertainment Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>

app/views/stats/weekly_geography.html.erb
<h3>Weekly Geography Stats</h3>

<h4>Email / Sum Geography Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Geography Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>

app/views/stats/weekly_history.html.erb
<h3>Weekly History Stats</h3>

<h4>Email / Sum History Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent History Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>

app/views/stats/weekly_science.html.erb
<h3>Weekly Science Stats</h3>

<h4>Email / Sum Science Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Science Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>

app/views/stats/weekly_sports.html.erb
<h3>Weekly Sports Stats</h3>

<h4>Email / Sum Sports Correct</h4>

<% @group_diff.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %>
<% end %>


<h4>Email /  Percent Sports Correct</h4>
<% @group_perc.each do |key, val| %>
  <p><%= User.find(key).email %> <%= val %></p>
<% end %>

<%= link_to "Back to Weekly Stats", weekly_stats_path %>